Sp24 225 implement multilingual support
computas/tekniskmuseum pull request #161
Opened 2024-07-02 10:10 UTC by jmehmandarova

2024-07-02 10:30 UTC, ComputasAlex requested changes
Bug seems to be fixed! 
Some language inconsistencies though:

![Skjermbilde 2024-07-02 kl  12 28 38](https://github.com/computas/tekniskmuseum/assets/116311019/092be1f8-6546-4c19-9b3d-391e7fd94cba)
![Skjermbilde 2024-07-02 kl  12 28 52](https://github.com/computas/tekniskmuseum/assets/116311019/361782f9-c982-457d-8d68-6b201b9cb15b)
![Skjermbilde 2024-07-02 kl  12 29 05](https://github.com/computas/tekniskmuseum/assets/116311019/159849ee-adbe-47bb-a918-eccb9d4e4fab)

2024-07-02 11:39 UTC, jmehmandarova commented
This PR was for bugfixes in frontend, pushed to develop on Friday

2024-07-03 06:32 UTC, ComputasAlex requested changes
Small issue, check review comments. Looking good other than that!

2024-07-03 06:32 UTC, ComputasAlex commented on src/app/game/game-draw/services/drawing.service.ts
> +  constructor(private http: HttpClient, private translationService: TranslationService) {}
Double constructor? Another constructor in lines 42-49 which I guess is the right one. Getting an error for this

2024-07-03 06:32 UTC, ComputasAlex commented on src/app/game/game-draw/services/drawing.service.ts
> +  constructor(private http: HttpClient, private translationService: TranslationService) {}
Also error for duplicate identifier 'http' but I assume this will be fixed by removing duplicate constructor

2024-07-03 08:26 UTC, ComputasAlex approved these changes

2024-07-03 08:27 UTC, ComputasAlex commented
Issues with multiplayer labels. Creating issue and fixing this asap rocky

2024-07-03 08:27 UTC, merged