Sp24 586 add back to menu button intermediate screen
computas/tekniskmuseum pull request #187
Opened 2024-07-15 11:21 UTC by sondrefj

## Changes
Add button on intermediate screen that navigates user back to main screen (where user can choose 1- or 2-player).
This works on multiplayer and singleplayer.

### Notes
I removed the "IO" logo that is in the upper left corner on the intermediate-screen to fit this button. Take a look at the provided screenshot. I can change this back, but when I think about it, we might consider removing the "IO"-logo from the game, since we use "I" and "O" as separate characters?

## UI 
![image](https://github.com/user-attachments/assets/e232caf7-7c4a-46c5-8308-aab9edf7d30c)

2024-07-15 12:04 UTC, andreasrberg requested changes

2024-07-15 12:04 UTC, andreasrberg commented on src/app/game/game-intermediate-result/game-intermediate-result-header/game-intermediate-result-header.component.ts
> +    this.router.navigate([routes.LANDING]);
This should probably route you to welcome screen instead? Since we agreed splash screen should only appear after idle timer

2024-07-16 07:59 UTC, ComputasAlex requested changes
Nice. Requesting change on mine and Andreas' comment

2024-07-16 07:59 UTC, ComputasAlex commented on src/app/game/game-intermediate-result/game-intermediate-result-header/game-intermediate-result-header.component.scss
> +.home-btn {
Could we add some feedback on click? And potentially hover? Can use the next-drawing/summary button for inspiration

2024-07-17 07:03 UTC, ComputasAlex approved these changes
Okay!

2024-07-17 07:05 UTC, andreasrberg approved these changes
🙌

2024-07-17 07:06 UTC, merged